### ISSUE TITLE
problem for accessing network?

### ISSUE THREAD

**Issue by tinaok** [pangeo-data/pangeo-eosc#43] opened 2022-10-21 05:12 UTC
We are trying to access some CMIP6 data available from ESGF server, and it is not working well.  
I'm trying to find out where the problem is coming from.  
I found out that following command works from my PC ( at home) and I can do wget, but I this does not work from https://pangeo-clivar.vm.fedcloud.eu/

```
(notebook) jovyan@jupyter-todaka:~/$ wget http://esgf-node2.cmcc.it/thredds/fileServer/esg_dataroot/CMIP6/OMIP/CMCC/CMCC-CM2-SR5/omip2/r1i1p1f1/Omon/vmo/gn/v20200226/vmo_Omon_CMCC-CM2-SR5_omip2_r1i1p1f1_gn_165301-171312.nc
--2022-10-20 11:01:19--  http://esgf-node2.cmcc.it/thredds/fileServer/esg_dataroot/CMIP6/OMIP/CMCC/CMCC-CM2-SR5/omip2/r1i1p1f1/Omon/vmo/gn/v20200226/vmo_Omon_CMCC-CM2-SR5_omip2_r1i1p1f1_gn_165301-171312.nc
Resolving esgf-node2.cmcc.it (esgf-node2.cmcc.it)... 193.204.199.223
Connecting to esgf-node2.cmcc.it (esgf-node2.cmcc.it)|193.204.199.223|:8          0... failed: Connection timed out.
Retrying.
```

Does anyone have idea how to fix this?

**Comment by sebastian-luna-valero** [comment] 2022-10-21 08:26
Did you consider downloading the data from Climate Data Store (CDS)?
https://cds.climate.copernicus.eu/cdsapp#!/dataset/projections-cmip6

cc @bschumac

**Comment by sebastian-luna-valero** [comment] 2022-10-21 11:27
I connected to pangeo-clivar and connection to the outside world in general works. It looks like the problem is with this particular set of servers.

Indeed the same `wget` command works on my personal computer but it doesn't on the JupyterHub session. 

My assumption is that several people connected to pangeo-clivar have tried to download the same file(s), the ESGF servers have detected all the requests coming from the same IP address and incoming connections from pangeo-clivar have been banned on the ESGF servers. Are there docs out there that we could check to confirm this? Or is there a ticketing system that we could use to report this on the ESGF side?

**Comment by tinaok** [comment] 2022-10-21 12:29
Thank you @sebastian-luna-valero 
I do not know about ticketing system exist or not in ESGF, I googled 'ESGF cmcc it' but didn't find anything which looks like 'support' May be I didn't search with right keywords...

Assuming it is the ESGF server side, I tried to find mirror servers.  
```
['http://esgf-node2.cmcc.it/thredds/fileServer/esg_dataroot/CMIP6/OMIP/CMCC/CMCC-CM2-HR4/omip2/r1i1p1f1/Omon/vmo/gn/v20200226/vmo_Omon_CMCC-CM2-HR4_omip2_r1i1p1f1_gn_200801-201812.nc',
 'https://esgf.ceda.ac.uk/thredds/fileServer/esg_cmip6/CMIP6/OMIP/CMCC/CMCC-CM2-HR4/omip2/r1i1p1f1/Omon/vmo/gn/v20200226/vmo_Omon_CMCC-CM2-HR4_omip2_r1i1p1f1_gn_200801-201812.nc',
 'http://esgf-data1.llnl.gov/thredds/fileServer/css03_data/CMIP6/OMIP/CMCC/CMCC-CM2-HR4/omip2/r1i1p1f1/Omon/vmo/gn/v20200226/vmo_Omon_CMCC-CM2-HR4_omip2_r1i1p1f1_gn_200801-201812.nc']
```

I could wget the one from esgf.ceda.ac.uk, so I'll try to ask users that they try this path while we find definite solution.  (& cross finger that  esgf.ceda.ac.uk does not block us..)

**Comment by floriankrb** [comment] 2022-10-24 12:41
[CliMetLab](https://climetlab.readthedocs.io/en/latest/examples/03-source-cds.html) may be of some help here. I am not sure which data you need, but downloading from the CDS does work "from the internet" for this CMPI6 data:
```
import climetlab as cml

ds = cml.load_source('cds', 'projections-cmip6',
   experiment= 'ssp1_1_9',
   temporal_resolution= 'monthly',
   variable= 'air_temperature',
   model= 'ec_earth3_veg',
   month= '01',
   year= ['2016','2032'],
   area= [ 50, -1, 30, 5,],
)
print(ds.to_xarray())
```

**Comment by sebastian-luna-valero** [comment] 2022-10-24 12:50
@tinaok also a reminder that `pangeo.admins` could host difficult-to-get data in a separate object store [1] that could be offered as read-only for trainees. In case it helps.

[1] https://github.com/pangeo-data/pangeo-eosc/blob/main/WEB-Object_storage-Creation.md

**Comment by sebastian-luna-valero** [comment] 2023-07-14 07:14
Closing as obsolete.

**Closed by sebastian-luna-valero** 2023-07-14 07:14 UTC
